//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{


    public partial class duaxe
    {
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Button btnAccelerate;
        protected global::System.Web.UI.WebControls.Button btnBrake;
        protected global::System.Web.UI.WebControls.Button btnLeft;
        protected global::System.Web.UI.WebControls.Button btnRight;
        protected global::System.Web.UI.WebControls.Button btnReset;

        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
